git:
  depth: 1

language: python

python:
  - 2.7

notifications:
  irc:
    channels:
      - irc.smoothirc.net#zds-dev
    skip_join: true

cache:
  - apt
  - pip

install:
  # APT Stuff
  - sudo apt-get update
  - sudo echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
  - sudo apt-get install ttf-mscorefonts-installer
  - sudo apt-get install texlive
  - sudo apt-get install texlive-xetex
  - sudo apt-get install texlive-lang-french
  - sudo apt-get install texlive-latex-extra

  # Cabal + Pandoc stuff
  - sudo mkdir -p ~/cabal/bin
  - sudo mkdir -p ~/.pandoc
  - sudo wget -P ~/cabal/bin https://dl.dropboxusercontent.com/u/18967337/pandoc
  - sudo wget -P ~/.pandoc/templates https://dl.dropboxusercontent.com/u/14517385/dev/default.epub
  - sudo wget -P ~/.pandoc/templates https://dl.dropboxusercontent.com/u/14517385/dev/default.html
  - sudo touch ~/.pandoc/epub.css
  - sudo touch ~/.pandoc/templates/epub.css
  - sudo chmod u+x,g+x,o+x ~/cabal/bin/pandoc
  - export PATH=$PATH:~/cabal/bin
  - sudo ~/cabal/bin/pandoc --version
  - sudo apt-get --reinstall install -qq language-pack-fr

  # Python dependencies
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coveralls

  # NodeJS + NPM stuff
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get -y update
  - sudo apt-get -y install nodejs
  - npm install -g bower gulp
  - npm install

script:
  - npm run-script travis
  - coverage run --source='.' manage.py test

after_success:
  - coveralls
